const axios = require('axios');

module.exports = async ({ req, res, log, error }) => {
  // Enhanced debugging
  log("--- NEW EXECUTION ---");
  log("Headers received:", JSON.stringify(req.headers));
  log("Raw body received:", req.body);
  log("Body type:", typeof req.body);

  try {
    // Check for empty body first
    if (!req.body || req.body === '') {
      error("Empty body detected");
      return res.json({ 
        statusCode: 400,
        error: "Request body cannot be empty",
        receivedBody: req.body
      });
    }

    // Parse the request
    let parsedRequest;
    try {
      // First parse the outer wrapper
      parsedRequest = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
      
      // Then parse the inner data payload
      if (parsedRequest.data) {
        try {
          parsedRequest = JSON.parse(parsedRequest.data);
        } catch (innerError) {
          error("Inner data parse error:", innerError);
          throw new Error(`Invalid inner data format: ${innerError.message}`);
        }
      }
    } catch (parseError) {
      error("Parse error:", parseError);
      return res.json({
        statusCode: 400,
        error: "Invalid request format",
        details: parseError.message,
        receivedBody: req.body
      });
    }

    log("Successfully parsed request:", parsedRequest);

    // Extract input text
    const inputText = parsedRequest.inputText || 
                     parsedRequest.text || 
                     (typeof parsedRequest === 'string' ? parsedRequest : null);

    if (!inputText || typeof inputText !== 'string') {
      throw new Error("Missing or invalid input text");
    }

    log("Processing input:", inputText.substring(0, 100));

    // Verify API key
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("Server configuration error - API key missing");
    }

    // Call Gemini API
    const geminiResponse = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [{ parts: [{ text: inputText }] }]
      },
      {
        headers: { "Content-Type": "application/json" },
        timeout: 30000
      }
    );

    // Process response
    const generatedText = geminiResponse.data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!generatedText) {
      throw new Error("No content generated by AI");
    }

    return res.json({
      statusCode: 200,
      output: generatedText
    });

  } catch (err) {
    error("Fatal error:", err.message, err.stack);
    return res.json({
      statusCode: err.message.includes("Invalid") ? 400 : 500,
      error: err.message,
      ...(process.env.NODE_ENV === 'development' && { stack: err.stack })
    });
  }
};